CREATE TABLE tasks
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid          UUID                                    NOT NULL,
    assignee_uuid UUID,
    description   VARCHAR(1000),
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

ALTER TABLE tasks
    ADD CONSTRAINT uc_tasks_uuid UNIQUE (uuid);